// supabase-config.js
export const SUPABASE_URL = "https://mnghhnshzzhmtozixyoe.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZ2hobnNoenpobXRveml4eW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzE5MjQsImV4cCI6MjA3MDI0NzkyNH0.VJ0ioBYhpWrGzwy3v6Jh10Sj4-qblzZPrIF04yyYVqk";

